### ISSUE TITLE
编译ko问题

### ISSUE THREAD

**Issue by MYSK-QC** [rogxo/kernel_hack#2]
make: 进入目录“/root/kernel_xiaomi_sm8350-miui/out”
  CC [M]  /root/kernel_xiaomi_sm8350-miui/drivers/wanbai/memory.o
  AR [M]  /root/kernel_xiaomi_sm8350-miui/drivers/wanbai/k.o
  LTO [M] /root/kernel_xiaomi_sm8350-miui/drivers/wanbai/k.lto.o
  Building modules, stage 2.
  MODPOST 1 modules
ERROR: "valid_phys_addr_range" [/root/kernel_xiaomi_sm8350-miui/drivers/wanbai/k.ko] undefined!
make[2]: *** [../scripts/Makefile.modpost:113：__modpost] 错误 1
make[1]: *** [/root/kernel_xiaomi_sm8350-miui/Makefile:1809：modules] 错误 2
make: *** [../Makefile:190：sub-make] 错误 2
make: 离开目录“/root/kernel_xiaomi_sm8350-miui/out”
请问这怎么搞

**Comment by rogxo** [comment]
可能你的内核源码里并没有valid_phys_addr_range，需要自己实现
